### ISSUE TITLE
Add a GitHub action that exercises the Bazel build path

### ISSUE THREAD

**Issue by mihaimaruseac** [slsa-framework/example-package#39]
This should prevent #23 from re-ocurring again.

If #38 lands as it is, with `gazelle`, we could even attempt to automatically fix the Bazel build when Go deps are updated/new ones are added.

**Comment by laurentsimon** [comment]
the bazel builder is an old builder which does not provide SLSA3. We can remove it and replace it with an example using the generic builder.

**Comment by mihaimaruseac** [comment]
Oh, that works too.

On the other end, I was thinking to maybe provide an example for Bazel projects too (e.g., TensorFlow), to lower barrier to entry.

**Comment by laurentsimon** [comment]
+1 on presenting a Bazel project for the build. You can then use the generic builder to generate the provenance.
See https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/generic as example. I think we're in the process of renaming the generic builder, and you'll have to pin it via a tag like `@v1.0.0` to pass verification.

We have not released. it yet, but you should be able try it.

@ianlewis any advice for @mihaimaruseac to test the generic builder before the official release?

**Comment by laurentsimon** [comment]
actually here's an example we use for the e2e tests (which uses the builder at HEAD): https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.generic.tag.main.default.slsa2.yml#L37-L82

You need to change the build part to checkout + build, then the rest is the same. You can ignore everything in this file, it's used to report failure/success of e2e tests.

**Comment by mihaimaruseac** [comment]
There seems to already exist one such action, but not run on PRs / as pre/post-submit check: https://github.com/slsa-framework/example-package/actions/workflows/github-actions-demo.yaml

**Comment by laurentsimon** [comment]
ah yeah, that's an old one and should be updated with the generic provenance generator. There were a few examples on the repo before we started working on the SLSA3 compliant project, and this is one of them.

**Comment by mihaimaruseac** [comment]
Sure, I'll look at #41 and previous links and send a PR shortly

**Comment by ianlewis** [comment]
An example workflow that should work in a repo like this one would like like this:

```yaml
name: SLSA provenance only
on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    outputs:
      digest: ${{ steps.hash.outputs.digest }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up golang environment
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.1.3
        with:
          go-version: 1.18
      - name: Checkout the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.3.4
        with:
          fetch-depth: 0
      - name: build
        shell: bash
        run: go build -o hello .
      - name: hash
        shell: bash
        id: hash
        run: |
          set -euo pipefail
          DIGEST=$(sha256sum hello | base64 -w0)
          echo "::set-output name=digest::$DIGEST"
      - name: Upload the artifact
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v2.3.1
        with:
          name: "hello"
          path: "hello"
          if-no-files-found: error
          retention-days: 5

  provenance:
    needs: [build]
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/slsa2_provenance.yml@v1.0.0
    with:
      base64-subjects: "${{ needs.build.outputs.digest }}"

  output:
    needs: [provenance]
    runs-on: ubuntu-latest
    steps:
      - env:
          PROVENANCE: ${{ needs.provenance.outputs.attestation-name }}
        run: |
          echo "provname: $PROVENANCE"
```
